INSERT INTO practice.symbols (symbol, name, exchange) VALUES
                                                          ('RELIANCE', 'Reliance Industries Limited', 'NSE'),
                                                          ('TCS', 'Tata Consultancy Services Limited', 'NSE'),
                                                          ('INFY', 'Infosys Limited', 'NSE'),
                                                          ('HDFCBANK', 'HDFC Bank Limited', 'NSE'),
                                                          ('ICICIBANK', 'ICICI Bank Limited', 'NSE'),
                                                          ('SBIN', 'State Bank of India', 'NSE'),
                                                          ('BHARTIARTL', 'Bharti Airtel Limited', 'NSE'),
                                                          ('ITC', 'ITC Limited', 'NSE'),
                                                          ('KOTAKBANK', 'Kotak Mahindra Bank Limited', 'NSE'),
                                                          ('LT', 'Larsen & Toubro Limited', 'NSE'),
                                                          ('HINDUNILVR', 'Hindustan Unilever Limited', 'NSE'),
                                                          ('AXISBANK', 'Axis Bank Limited', 'NSE'),
                                                          ('ASIANPAINT', 'Asian Paints Limited', 'NSE'),
                                                          ('MARUTI', 'Maruti Suzuki India Limited', 'NSE'),
                                                          ('SUNPHARMA', 'Sun Pharmaceutical Industries Limited', 'NSE'),
                                                          ('TITAN', 'Titan Company Limited', 'NSE'),
                                                          ('BAJFINANCE', 'Bajaj Finance Limited', 'NSE'),
                                                          ('WIPRO', 'Wipro Limited', 'NSE'),
                                                          ('ULTRACEMCO', 'UltraTech Cement Limited', 'NSE'),
                                                          ('NESTLEIND', 'Nestle India Limited', 'NSE'),
                                                          ('POWERGRID', 'Power Grid Corporation of India Limited', 'NSE'),
                                                          ('NTPC', 'NTPC Limited', 'NSE'),
                                                          ('TATASTEEL', 'Tata Steel Limited', 'NSE'),
                                                          ('M&M', 'Mahindra & Mahindra Limited', 'NSE'),
                                                          ('JSWSTEEL', 'JSW Steel Limited', 'NSE'),
                                                          ('TATAMOTORS', 'Tata Motors Limited', 'NSE'),
                                                          ('GRASIM', 'Grasim Industries Limited', 'NSE'),
                                                          ('TECHM', 'Tech Mahindra Limited', 'NSE'),
                                                          ('HDFCLIFE', 'HDFC Life Insurance Company Limited', 'NSE'),
                                                          ('SBILIFE', 'SBI Life Insurance Company Limited', 'NSE')
    ON CONFLICT (symbol) DO NOTHING;