
-- V1__baseline.sql  (auth service)


CREATE TABLE auth.users (
                            id              uuid NOT NULL,
                            phone           character varying(255) NOT NULL,
                            name            character varying(255) NOT NULL,
                            password_hash   character varying(255) NOT NULL,
                            created_at      timestamp with time zone DEFAULT now() NOT NULL,
                            email           character varying(255) NOT NULL,
                            email_verified  boolean NOT NULL,
                            updated_at      timestamp(6) with time zone NOT NULL,
                            CONSTRAINT users_pkey PRIMARY KEY (id),
                            CONSTRAINT uk_users_phone UNIQUE (phone),
                            CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
    -- NOTE: ukdu5v5sr43g5bfnji4vb8hg5s3 is a duplicate UNIQUE(phone) constraint
    -- created by repeated ddl-auto=update runs. Safe to drop later;
);

CREATE TABLE auth.otp (
                          id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          email       character varying(255),
                          expires_at  timestamp(6) without time zone,
                          otp         character varying(255),
                          verified    boolean NOT NULL,
                          CONSTRAINT otp_pkey PRIMARY KEY (id)
);

CREATE TABLE auth.refresh_tokens (
                                     id          uuid NOT NULL,
                                     user_id     uuid NOT NULL,
                                     token_hash  character varying(255) NOT NULL,
                                     expires_at  timestamp with time zone NOT NULL,
                                     revoked     boolean DEFAULT false NOT NULL,
                                     CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
                                     CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
                                     CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_token_hash ON auth.refresh_tokens USING btree (token_hash);
CREATE INDEX idx_refresh_tokens_user_id ON auth.refresh_tokens USING btree (user_id);