name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI Pipeline
        run: echo "PaiseWise Backend CI pipeline triggered successfully"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Static Code Analysis
        run: mvn checkstyle:check

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Security Scan
        run: mvn org.owasp:dependency-check-maven:check
