name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Step 4 - Trigger Pipeline
      - name: Run CI Pipeline
        run: echo "PaiseWise Backend CI pipeline triggered successfully"
# Step 5 - Checkout Source Code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify pom.xml
        run: |
          pwd
          ls -la
          find . -name pom.xml -print

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Dependencies
        run: mvn dependency:resolve

      - name: Static Code Analysis
        run: mvn checkstyle:check

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Security Scan
        run: mvn org.owasp:dependency-check-maven:check
      
      
      
