name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Step 4 - Trigger Pipeline
      - name: Run CI Pipeline
        run: echo "PaiseWise Backend CI pipeline triggered successfully"
# Step 5 - Checkout Source Code
      - name: Checkout code
        uses: actions/checkout@v4
      
      
